// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpg_m2p65HhhGPEZCbtvgqbWtSMd7CvA4',
    appId: '1:913021835931:web:d188491fc546b0046fc43e',
    messagingSenderId: '913021835931',
    projectId: 'imonkfcwifirnfmaehdtks',
    authDomain: 'imonkfcwifirnfmaehdtks.firebaseapp.com',
    storageBucket: 'imonkfcwifirnfmaehdtks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9W-JStQfwPMW0Fnh0OUnbD4swoxwWqkg',
    appId: '1:913021835931:android:d2431db3e18d87b06fc43e',
    messagingSenderId: '913021835931',
    projectId: 'imonkfcwifirnfmaehdtks',
    storageBucket: 'imonkfcwifirnfmaehdtks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOJrbhxWBkD1UkS0ISEXqidBsbZTkmHE',
    appId: '1:913021835931:ios:9f43c8864e7ef2486fc43e',
    messagingSenderId: '913021835931',
    projectId: 'imonkfcwifirnfmaehdtks',
    storageBucket: 'imonkfcwifirnfmaehdtks.appspot.com',
    iosClientId: '913021835931-6kvsicmlq45bls5pbcr6ifji5m27vmp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pleaseWork',
  );
}
